### PR TITLE
Fix Tutorial View

### LINKED ISSUE #217: The tutorial view and modal's content is being cut off to the right

### PR DESCRIPTION
**Pull request by noahmalmed**
Fixes #217 

# Changes
Refactored how the tutorial is displayed. It is now displayed as a paginating scroll view. Appearance-wise it looks identical, but it fixes a visual issue where the image load lags behind the markdown load.

Using a paginating scrollview, all of the content loads at once. This means the transition is smooth between pages.

Also, fix a bug that caused a crash with image caching.

# Review Checklist

- [x] Does it work in Android and iOS?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Are tests passing?

### CODE REVIEW

File: src/components/classifier/Tutorial.js [hunk 1]
```diff
@@ -23,23 +23,27 @@ export class Tutorial extends Component {
...
 
   render() {
     const steps = this.props.tutorial.steps
-    const step = steps[this.state.step]
     const totalSteps = length(steps)
-
-    const mediaResource = (step.media ? this.props.tutorial.mediaResources[step.media] : null )
-    const mediaImage = (mediaResource !== null ? <SizedImage source={{ uri: mediaResource.src }} /> : null)
+    
+    const tutorialStep = steps.map((step, index) => {
```
Comment (wgranger) [inline src/components/classifier/Tutorial.js]: This should probably be `tutorialSteps` plural

File: src/components/classifier/Tutorial.js [hunk 2]
```diff
@@ -23,23 +23,27 @@ export class Tutorial extends Component {
...
+      return (
+        <TutorialStep
+          key={`${index}`}
```
Comment (wgranger) [inline src/components/classifier/Tutorial.js]: Might be safer here to make the key `TUTORIAL_STEP_${index}` or something similar to avoid the key from interfering with any other z-indexed keys in the view.

**Comment by noahmalmed** [comment]
@wgranger updated per your review

File: src/components/classifier/Tutorial.js [hunk 3]
```diff
@@ -69,7 +69,7 @@ export class Tutorial extends Component {
     const renderCircle = (currentStep, index) => {
       return (
         <TouchableOpacity
-          key={ index }
+          key={ `PAGINATION_DOT_${index}` }
```
Comment (wgranger) [inline src/components/classifier/Tutorial.js]: Good catch here. Didn't see this the first time around.

**Comment by wgranger** [comment]
Looks good. Thanks for the update.
